---
repos:
  - repo: https://github.com/PyCQA/doc8
    rev: 0.11.2
    hooks:
      - id: doc8
        name: doc8
        description: This hook runs doc8 for linting docs.
        entry: python -m doc8
        language: python
        files: \.rst$
        require_serial: true
  - repo: https://github.com/psf/black.git
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        exclude: ^(tests\/hooks-abort-render\/hooks|docs\/HelloCookieCutter1)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending
      - id: fix-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
        exclude: "invalid-syntax.json|tests/fake-repo-bad-json/cookiecutter.json|tests/fake-repo/cookiecutter.json"
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        exclude: "not_rendered.yml|invalid-config.yaml"
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-absolute-import
          - flake8-black
          - flake8-docstrings
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: [--ini, .bandit]
  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.48"
    hooks:
    -   id: check-manifest