name: Release Drafter

on:
  push:
    branches:
      - master
  # autolabeler
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
